package learn.home.repository;


public class DatabaseCommands {

    public static final String CREATE_SCHEMA = "CREATE SCHEMA patients\n" +
            "    AUTHORIZATION postgres;";

    public static final String CREATE_TABLE = "CREATE TABLE patients.patient\n" +
            "(\n" +
            "    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n" +
            "    \"fName\" character(255) NOT NULL,\n" +
            "    \"lName\" character(255) NOT NULL,\n" +
            "    \"cEmail\" character varying(255) NOT NULL,\n" +
            "    \"phoneNumber\" character varying(255),\n" +
            "    PRIMARY KEY (id)\n" +
            ");";
    public static final String ADD_PATIENT = "INSERT INTO patients.patient(\"fName\",\"lName\",\"cEmail\",\"phoneNumber\") VALUES (?,?,?,?)";

    public static final String GET_ALL = "SELECT * FROM patients.patient";

    public static final String FIND_BY_ID = "SELECT * FROM patients.patient WHERE \"id\" = ?";

    public static final String FIND_BY_NAME = "SELECT * FROM patients.patient WHERE \"fName\" = ?";

    public static final String FIND_BY_SURNAME = "SELECT * FROM patients.patient WHERE \"lName\" = ?";

  }
// public static final String FIND_BY_PHONENUMBER ="SELECT * FROM patients.patient WHERE \"phoneNumber\" = ?";

//public static final String DELETE = "DELETE FROM patients.patient where \"id\" = ?";
